#!/usr/bin/env bash
#changes listen port in enabled default site from 8080 to 80
sed -i "s/listen 8080/listen 80/" /etc/nginx/sites-enabled/default
sed -i "s/listen \[::\]:8080/listen \[::\]:80/" /etc/nginx/sites-enabled/default
service nginx restart
