#!/usr/bin/env bash
#output "Holberton School", except iterations 4 and 8
i=0
while [ $i -lt 10 ]; do
    ((i++))
    if [ $i -eq 4 ]; then
	echo bad luck
    elif [ $i -eq 8 ]; then
	echo good luck
    else
	echo Holberton School
    fi
done
