#!/usr/bin/env bash
#output a squence of numbers resembling a clock counter
hour=0
while [ $hour -lt 24 ]; do
    echo Hour: $hour
    minute=0
    while [ $minute -lt 60 ]; do
	echo $minute
	((minute++))
    done
    ((hour++))
done
