#!/usr/bin/env bash
#install an nginx server and change index page to string "Holberton School"
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School for the win!" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
