#!/usr/bin/env bash
#install an nginx server and change index page to string "Holberton School"
apt-get update
apt-get -y install nginx
echo "Holberton School for the win!" > /usr/share/nginx/html/index.html
