#!/usr/bin/env bash
#install an nginx server and change index page to string "Holberton School"
apt-get update
sudo apt-get -y install nginx
echo "Holberton School for the win!" |
    sudo tee /usr/share/nginx/html/index.html
sudo sed -i "/# Only for*/i\\
        rewrite \^\/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4\
 permanent;\n" /etc/nginx/sites-available/default
sudo service nginx restart
