#!/usr/bin/env bash
#install an nginx server and change index page to string "Holberton School"
apt-get update
sudo apt-get -y install nginx
echo "Holberton School for the win!" |
    sudo tee /usr/share/nginx/html/index.html
sudo sed -i "/http {/a\\
        server {\n\
	server_name 35.237.144.252;\n\
        rewrite \^\/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4\
 permanent;\n}" /etc/nginx/nginx.conf
sudo service nginx restart
sudo nginx -s reload
