#!/usr/bin/env bash
#install an nginx server and change index page to string "Holberton School"
sudo apt-get -y install nginx
echo "Holberton School for the win!" |
    sudo tee /usr/share/nginx/html/index.html
#set server up to redirect /redirect_me to nyan cat
sudo sed -i "/http {/a\\
        server {\n\
	server_name 35.237.144.252;\n\
        rewrite \^\/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4\
 permanent;\n\
 error_page 404 \/404.html;\n\}" /etc/nginx/nginx.conf
sudo nginx -s reload
